# Generated by Django 4.0.3 on 2022-04-02 07:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_alter_restaurant_restaurantname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Drink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkName', models.CharField(max_length=100)),
                ('drinkCategory', models.CharField(max_length=100)),
                ('drinkDescription', models.CharField(max_length=10000)),
                ('drinkDiscountcode', models.CharField(max_length=50)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='drinkScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkSize', models.CharField(max_length=100)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drinkComment', models.CharField(max_length=10000)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
            ],
        ),
    ]
