# Generated by Django 4.0.2 on 2022-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='drinkImage',
            field=models.ImageField(default='asdf', upload_to='images/'),
            preserve_default=False,
        ),
    ]
