# Generated by Django 4.0.2 on 2022-04-16 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('drink', '0002_drink_drinkimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='drink',
            name='price',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
