# Generated by Django 4.0.2 on 2022-04-17 11:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0002_remove_foodorder_food_id_remove_order_customer_id_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('drink', '0003_drink_price'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrinkComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=240)),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.RenameField(
            model_name='drinkreview',
            old_name='customer_id',
            new_name='userId',
        ),
        migrations.RemoveField(
            model_name='drinkreview',
            name='drinkComment',
        ),
        migrations.AddField(
            model_name='drinkreview',
            name='liked',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='drinkreview',
            name='rating',
            field=models.IntegerField(default=0),
        ),
        migrations.DeleteModel(
            name='drinkScale',
        ),
    ]
