# Generated by Django 4.0.3 on 2022-04-01 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='restaurantName',
            field=models.CharField(default='', max_length=80),
        ),
    ]
