# Generated by Django 4.0.3 on 2022-04-01 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_restaurant_restaurantname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='restaurant',
            name='restaurantName',
            field=models.CharField(max_length=80),
        ),
    ]
