# Generated by Django 4.0.2 on 2022-04-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0003_alter_restaurant_restaurantname'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='password',
            field=models.CharField(default='Sum', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantImage',
            field=models.ImageField(default='Sum', upload_to='images/'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantInfro',
            field=models.CharField(default='Sum', max_length=250),
            preserve_default=False,
        ),
    ]
