# Generated by Django 4.0.2 on 2022-04-10 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0004_restaurant_password_restaurant_restaurantimage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='minimumOrder',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='closingTime',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='restaurant',
            name='openingTime',
            field=models.CharField(max_length=100),
        ),
    ]
