# Generated by Django 4.0.2 on 2022-04-10 05:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0005_restaurant_minimumorder_alter_restaurant_closingtime_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='restaurantInfro',
            new_name='restaurantInfo',
        ),
    ]
