# Generated by Django 4.0.2 on 2022-04-10 14:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0006_rename_restaurantinfro_restaurant_restaurantinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurantreview',
            name='RestaurantLiked',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurantComment',
            field=models.CharField(default='', max_length=10000),
        ),
        migrations.AlterField(
            model_name='restaurantreview',
            name='restaurantRating',
            field=models.IntegerField(default=0),
        ),
    ]
