# Generated by Django 4.0.2 on 2022-04-10 16:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0007_restaurantreview_restaurantliked_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='RestaurantComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=240)),
            ],
        ),
        migrations.RemoveField(
            model_name='restaurantreview',
            name='restaurantComment',
        ),
        migrations.AddField(
            model_name='restaurant',
            name='restaurantPhonenumber',
            field=models.CharField(default=9800000000, max_length=20),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='RestaurantContact',
        ),
        migrations.AddField(
            model_name='restaurantcomment',
            name='restaurant_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant'),
        ),
        migrations.AddField(
            model_name='restaurantcomment',
            name='user_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
