# Generated by Django 4.0.2 on 2022-04-10 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0008_restaurantcomment_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='cusine',
            field=models.CharField(default='Multi cusine', max_length=200),
            preserve_default=False,
        ),
    ]
