# Generated by Django 4.0.2 on 2022-04-19 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0009_restaurant_cusine'),
    ]

    operations = [
        migrations.AddField(
            model_name='restaurant',
            name='sponsered',
            field=models.BooleanField(default=False),
        ),
    ]
