# Generated by Django 4.0.2 on 2022-04-19 07:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0010_restaurant_sponsered'),
    ]

    operations = [
        migrations.RenameField(
            model_name='restaurant',
            old_name='sponsered',
            new_name='sponsored',
        ),
    ]
