# Generated by Django 4.0.3 on 2022-04-02 08:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0003_alter_restaurant_restaurantname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Food',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodName', models.CharField(max_length=200)),
                ('foodCategory', models.CharField(max_length=200)),
                ('foodDiscountcode', models.CharField(max_length=30)),
                ('foodDescription', models.CharField(max_length=200)),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='FoodScale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodSize', models.CharField(max_length=100)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
        migrations.CreateModel(
            name='FoodReview',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('foodComment', models.CharField(max_length=10000)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
    ]
