# Generated by Django 4.0.2 on 2022-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='foodImage',
            field=models.ImageField(default='', upload_to='images/'),
            preserve_default=False,
        ),
    ]
