# Generated by Django 4.0.2 on 2022-04-21 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_foodcomment_rename_customer_id_foodreview_userid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='food',
            name='date',
            field=models.DateField(default='2022-04-21'),
            preserve_default=False,
        ),
    ]
