# Generated by Django 4.0.3 on 2022-04-02 08:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Food', '0001_initial'),
        ('drink', '0001_initial'),
        ('restaurant', '0003_alter_restaurant_restaurantname'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchaseMethod', models.CharField(max_length=200)),
                ('customer_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('drinkScale_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='drink.drinkscale')),
                ('foodScale_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='Food.foodscale')),
            ],
        ),
        migrations.CreateModel(
            name='OrderRestaurant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
                ('restaurant_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
            ],
        ),
        migrations.CreateModel(
            name='FoodOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Food_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
            ],
        ),
        migrations.CreateModel(
            name='DrinkOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('drink_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
            ],
        ),
    ]
