# Generated by Django 4.0.2 on 2022-04-17 11:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='foodorder',
            name='Food_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='customer_id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='drinkScale_Id',
        ),
        migrations.RemoveField(
            model_name='order',
            name='foodScale_Id',
        ),
        migrations.RemoveField(
            model_name='orderrestaurant',
            name='order_id',
        ),
        migrations.RemoveField(
            model_name='orderrestaurant',
            name='restaurant_id',
        ),
        migrations.DeleteModel(
            name='DrinkOrder',
        ),
        migrations.DeleteModel(
            name='FoodOrder',
        ),
        migrations.DeleteModel(
            name='Order',
        ),
        migrations.DeleteModel(
            name='OrderRestaurant',
        ),
    ]
