# Generated by Django 4.0.2 on 2022-04-18 05:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Food', '0004_foodcomment_rename_customer_id_foodreview_userid_and_more'),
        ('drink', '0004_drinkcomment_rename_customer_id_drinkreview_userid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Order', '0002_remove_foodorder_food_id_remove_order_customer_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('notes', models.CharField(blank=True, max_length=255, null=True)),
                ('drinkId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
                ('foodId', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
