# Generated by Django 4.0.2 on 2022-04-19 10:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Food', '0004_foodcomment_rename_customer_id_foodreview_userid_and_more'),
        ('drink', '0004_drinkcomment_rename_customer_id_drinkreview_userid_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('restaurant', '0011_rename_sponsered_restaurant_sponsored'),
        ('Order', '0003_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('totalPrice', models.IntegerField()),
                ('restaurantDelivered', models.BooleanField(default=False)),
                ('userReceived', models.BooleanField(default=False)),
                ('paymentDone', models.BooleanField(default=False)),
                ('paymentByCash', models.BooleanField(default=True)),
                ('forDonating', models.BooleanField(default=False)),
                ('preOrderDate', models.DateField(blank=True, null=True)),
                ('restaurant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='restaurant.restaurant')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('drink', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='drink.drink')),
                ('food', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Food.food')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Order.order')),
            ],
        ),
    ]
