# Generated by Django 4.0.2 on 2022-04-19 13:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0004_order_orderitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='notes',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
