# Generated by Django 4.0.2 on 2022-04-19 13:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Order', '0005_orderitem_notes'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='location',
            field=models.CharField(default='Dharan', max_length=255),
            preserve_default=False,
        ),
    ]
