# Generated by Django 4.0.2 on 2022-04-10 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignUp', '0002_alter_customeruser_groups_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='customerLocation',
            field=models.CharField(default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='customerName',
            field=models.CharField(default='', max_length=80, null=True),
        ),
    ]
