# Generated by Django 4.0.2 on 2022-04-16 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('LoginSignUp', '0003_alter_customeruser_customerlocation_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customeruser',
            name='customerLocation',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
        migrations.AlterField(
            model_name='customeruser',
            name='customerName',
            field=models.CharField(blank=True, default='', max_length=80, null=True),
        ),
    ]
